### PR TITLE
Some README updates.

### PR DESCRIPTION
**Pull request by AustinT**
1. Change environment name to `adkf-fsmol`: it's more specific and won't conflict with existing FS-Mol environments.
2. Add explicit instructions to create environment and download dataset (before it took a bit of searching)
3. Replace `/path/to/dataset` with the actual path one gets from downloading the dataset (it was not completely clear what path to use)

### CODE REVIEW

**Comment by AustinT** [comment]
Ultimately I think it would be nice to include pre-trained model weights and link to those in the README, and replace things like `{model_name}` with the actual string that the user should use (it's not clear whether it should be "ADKF" or something like "FSMol_ADKTModel_gnn+ecfp+fc_2023-02-08_09-56-57").

@Wenlin-Chen maybe you could make an extra commit to this branch making these changes?

**Comment by AustinT** [comment]
@Wenlin-Chen  I see you changed the name of the environment in `README.md` but not in `environment.yml`, was that intentional?

**Comment by AustinT** [comment]
> @AustinT I have updated the README file. Where do you think we should upload the model weights to (figshare or this repo)? The size of the model weight file is about 100MB.

Can the 100MB size be reduced by zipping, or is this already zipped?

**Comment by Wenlin-Chen** [comment]
> @Wenlin-Chen one potential issue with the `README` now is that the different code snippets are not runnable in isolation: they would need to run the line `dataset_dir=...` in the same shell, which may not be immediately obvious.

Ok, that's a good point. I'll change it back

**Comment by Wenlin-Chen** [comment]
> > @AustinT I have updated the README file. Where do you think we should upload the model weights to (figshare or this repo)? The size of the model weight file is about 100MB.
> 
> Can the 100MB size be reduced by zipping, or is this already zipped?

It's not zipped. I'll zip it and see how much the size can be reduced

**Comment by Wenlin-Chen** [comment]
> > @AustinT I have updated the README file. Where do you think we should upload the model weights to (figshare or this repo)? The size of the model weight file is about 100MB.
> 
> Can the 100MB size be reduced by zipping, or is this already zipped?

We have two weight files (classification & regression), so 200MB in total. With highest zip compression level, the zipped file is 178MB.

**Comment by AustinT** [comment]
> > > @AustinT I have updated the README file. Where do you think we should upload the model weights to (figshare or this repo)? The size of the model weight file is about 100MB.
> > 
> > 
> > Can the 100MB size be reduced by zipping, or is this already zipped?
> 
> We have two weight files (classification & regression), so 200MB in total. With highest zip compression level, the zipped file is 178MB.

Let's put it on Figshare or Zenodo then? Both are good options I think.

**Review by Wenlin-Chen — APPROVED** [review]
@AustinT Thanks! I'll merge it now

**Pull request merged**
